# .github/workflows/test-and-report.yml

name: Test & Report (Single File)

on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    name: "Run single test: tests/test_example.py"
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest on tests/test_example.py
        run: |
          pytest tests/test_example.py \
            --json-report \
            --json-report-file=report-single.json \
            -q

      - name: Upload JSON report artifact
        uses: actions/upload-artifact@v2.2.0
        with:
          name: report
          path: report-single.json
          if-no-files-found: error
          retention-days: 90