name: single_test

# ◆ Give GITHUB_TOKEN write access so we can create + upload artifacts
permissions:
  contents: read
  actions: write

on:
  workflow_dispatch:   # or push/pull_request
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - uses: actions/checkout@v3
        if: success() || failure()
      - name: Run pytest on tests/test_example.py
        run: |
          cd tests
          mkdir -p reports 
          pytest tests/test_example.py --json-report --json-report-file=report-single.json -q
          chmod 777  /home/runner/work/test_CI/test_CI/tests/reports/

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=tests/reports/" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-report
          path: ${{ steps.results.outputs.artifactPath }}